### ISSUE TITLE
[RFC] A Bottles' installer manifest

### ISSUE THREAD

**Issue by RushingAlien** [cryinkfly/Autodesk-Fusion-360-for-Linux#231]
Hell there, not sure if RFC is the appropriate here! I am currently attempting to write a Bottles' installer manifest for fusion360, however I seem to be hitting bug #215 and ommiting --quiet from the second install phase does not help, I am asking for feedback.
![gambar](https://user-images.githubusercontent.com/80886145/170854629-ba6f8f83-4344-4904-a114-84a3c1215bee.png)

```yaml
Name: fusion360
Description : Fusion 360 is a cloud-based 3D CAD, CAM & CAE design tool from Autodesk. It is available on a number of platforms including Windows, Mac & In-Browser.
Grade : Bronze
Arch: win64

Dependencies:
- atmlib
- gdiplus
- msxml4
- msxml6
- vcredist2019
- winhttp

Executable:
  name: Fusion 360
  icon: fusion360.png
  file: fusion360.exe
  path: userdir/AppData/Roaming/Microsoft/Windows/Start Menu/Fusion360.lnk
  arguments: ""

Parameters:
  dxvk: true
  sync: esync

Steps:
- action: install_exe
  file_name: Fusion 360 Admin Install.exe
  url: https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe
  rename: Fusion360installer.exe
  file_checksum: 4d7f2df94b6e87074dfdacf329e63ecb
  arguments: -p deploy -g -f log.txt --quiet
  
- action: install_exe
  file_name: Fusion 360 Admin Install.exe
  url: https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe
  rename: Fusion360installer.exe
  file_checksum: 4d7f2df94b6e87074dfdacf329e63ecb
  arguments: -p deploy -g -f log.txt --quiet
```
docs : 
https://maintainers.usebottles.com
https://github.com/bottlesdevs/programs
